name: DocToHTML
on:
    push:
    schedule:
        - cron: "0 0 * * *"

jobs:
    run_script:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout reposotory
              uses: actions/checkout@v4

            - name: Get credential.json
              uses: jsdaniell/create-json@v1.2.3
              with:
                name: credential.json
                json: ${{ secretS.CREDENTIAL }}
                dir: ""

            - name: setup python
              uses: actions/setup-python@v6
              with:
                  python-version: "3.13"

            - name: install Python Packages
              run: pip install -r requirements.txt

            - name: Execute script
              run: python DocToHTML_Drive.py

            - name: Commit changes
              run: git config --local user.user "Github Action"
                  git config --local user.email "action@github.com"
                  git add -A
                  gi commit -m "GDD Update by Github Action"

            - name: Push changes
              uses: ad-m/github-push-action@v1.0.0
              with:
                  github_token: ${{ secrets.GH_TOKEN }}
