name: DocToHTML
on:
    push:
    schedule:
        - cron: "0 0 * * *"

jobs:
    run_script:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout reposotory
              uses: actions/checkout@v4

            - name: Get credential.json
              uses: jsdaniell/create-json@v1.2.3
              with:
                name: credential.json
                json: ${{ secrets.CREDENTIAL }}
                dir: ""

            - name: Setup Browser
              uses: abhi1693/setup-browser@v0.3.5
              id: setup-browser
              with: 
                browser: "chrome"
                

            # - name: Setup Chrome
            #   uses: browser-actions/setup-chrome@v2.1.0
            #   id: setup-chrome
            #   with:
            #     install-dependencies: true
            #     install-chromedriver: true
            # - run: |
            #    echo "path = ${{ steps.setup-chrome.outputs.chrome-path }}" >> $GITHUB_OUTPUT

            - name: setup python
              uses: actions/setup-python@v6
              with:
                  python-version: "3.13"


            #From https://github.com/MarketingPipeline/Python-Selenium-Action
            - name: Installing package list
              run: apt list --installed    

            - name: Removing previous chrome instances on runner 
              run: sudo apt purge google-chrome-stable  
              
            # Need to fetch reqs if needed
            - name: Installing all necessary packages
              run: pip install chromedriver-autoinstaller selenium pyvirtualdisplay
            - name: Install xvfb
              run: sudo apt-get install xvfb

            - name: Set virtual enviroment
              run: |
                python3 -m venv .venv
                source my_venv/bin/activate

            - name: List files in the repository (github.workspace)
              run: |
                ls ${{ github.workspace }}


            - name: install Python Packages
              run: pip install -r requirements.txt


            - name: Disable AppArmor
              run: |
                echo 0 | sudo tee /proc/sys/kernel/apparmor_restrict_unprivileged_userns

            # - name: Setup for starting Chrome
            #   run: |
            #       sudo apt-get install -y xvfb
            #       sudo apt-get -y install xorg xvfb gtk2-engines-pixbuf
            #       sudo apt-get -y install dbus-x11 xfonts-base xfonts-100dpi xfonts-75dpi xfonts-cyrillic xfonts-scalable
            #       sudo apt-get -y install imagemagick x11-apps
            #       Xvfb -ac :99 -screen 0 1280x1024x16 &
            #       export DISPLAY=:99

            - name: Execute script
              run: python DocToHTML_Drive.py
              env:
                CHROME_PATH: ${{steps.setup-browser.outputs.path}}

            - name: Commit changes
              run: git config --local user.user "Github Action"
                  git config --local user.email "action@github.com"
                  git add -A
                  gi commit -m "GDD Update by Github Action"

            - name: Push changes
              uses: ad-m/github-push-action@v1.0.0
              with:
                  github_token: ${{ secrets.GH_TOKEN }}
